<?php

declare(strict_types = 1);

namespace Drupal\restic_backup\Service;

use Drupal\Core\Cache\CacheBackendInterface;
use Drupal\Core\File\FileSystemInterface;
use Symfony\Component\Process\Process;

/**
 * Service for discovering and categorizing project files for backup.
 *
 * Implements intelligent file discovery based on:
 * - .gitignore rules
 * - Drupal-specific patterns (regenerable files, config)
 * - Sensitivity detection (encryption-gated files)
 * - Background caching for instant form loading
 */
class FileDiscoveryService {

  /**
   * The file system service.
   */
  protected FileSystemInterface $fileSystem;

  /**
   * The cache backend.
   */
  protected CacheBackendInterface $cache;

  /**
   * The project root directory.
   */
  protected string $projectRoot;

  /**
   * Cache key for file scan results.
   */
  const CACHE_KEY = 'restic_backup.file_scan_results';

  /**
   * Cache key for previous scan (for new file detection).
   */
  const CACHE_KEY_PREVIOUS = 'restic_backup.file_scan_previous';

  /**
   * Constructs a FileDiscoveryService object.
   *
   * @param \Drupal\Core\File\FileSystemInterface $file_system
   *   The file system service.
   * @param \Drupal\Core\Cache\CacheBackendInterface $cache
   *   The cache backend.
   */
  public function __construct(FileSystemInterface $file_system, CacheBackendInterface $cache) {
    $this->fileSystem = $file_system;
    $this->cache = $cache;
    $this->projectRoot = $this->getProjectRoot();
  }

  /**
   * Scan entire Drupal project and categorize files for backup.
   *
   * @param callable|null $progress_callback
   *   Optional callback to report progress during scan.
   * @param bool $use_cache
   *   Whether to use cached results (default TRUE for performance).
   *
   * @return array
   *   Nested array structure with categorized files and metadata.
   *
   * @throws \Exception
   *   If .gitignore not found or git not available.
   */
  public function scanProject(callable $progress_callback = NULL, bool $use_cache = TRUE): array {
    // Check cache first if enabled
    if ($use_cache) {
      $cached = $this->cache->get(self::CACHE_KEY);
      if ($cached !== FALSE && !empty($cached->data)) {
        return $cached->data;
      }
    }
    // 1. VALIDATE PREREQUISITES.
    if (!$this->hasGitignore()) {
      throw new \Exception('No .gitignore found. Cannot auto-detect files.');
    }
    if (!$this->gitAvailable()) {
      throw new \Exception('git command not available. Required for .gitignore parsing.');
    }

    // 2. INITIALIZE CATEGORIES.
    $categories = [
      'public_files' => ['included' => [], 'excluded_regenerable' => []],
      'private_files' => ['paths' => [], 'requires_encryption' => TRUE],
      'sensitive_config' => ['paths' => [], 'requires_encryption' => TRUE],
      'dependencies' => [],
      'regenerable' => ['informational' => []],
      'metadata' => [
        'gitignore_found' => TRUE,
        'total_size_bytes' => 0,
        'total_files' => 0,
      ],
    ];

    // 3. SCAN PROJECT ROOT.
    $allFiles = $this->recursiveFileScan($this->projectRoot);

    // 4. CATEGORIZE EACH FILE.
    $total_files = count($allFiles);
    $processed = 0;
    foreach ($allFiles as $filepath) {
      // Report progress every 100 files
      if ($progress_callback && $processed % 100 === 0) {
        call_user_func($progress_callback, $processed, $total_files);
      }
      $processed++;
      $relativePath = str_replace($this->projectRoot . '/', '', $filepath);

      // 4a. Skip dependencies FIRST (fast string match, avoids slow git calls).
      if ($this->isDependency($relativePath)) {
        $categories['dependencies'][] = $relativePath;
        continue;
      }

      // 4b. Skip files tracked by git (already in version control).
      // This module backs up files NOT in git (user uploads, local settings, etc.)
      if (!$this->isIgnoredByGit($relativePath)) {
        continue;
      }

      // 4c. Check if it's regenerable.
      if ($this->isRegenerableFile($relativePath)) {
        $categories['regenerable']['informational'][] = [
          'path' => $relativePath,
          'reason' => 'Auto-generated by Drupal (image styles, CSS/JS aggregation, cache)',
        ];
        continue;
      }

      // 4d. Check if it's sensitive config.
      if ($this->isSensitiveConfig($relativePath)) {
        $categories['sensitive_config']['paths'][] = [
          'path' => $relativePath,
          'type' => $this->getSensitiveConfigType($relativePath),
          'size' => filesize($filepath),
        ];
        continue;
      }

      // 4e. Check if it's private files.
      if ($this->isPrivateFile($relativePath)) {
        $categories['private_files']['paths'][] = [
          'path' => $relativePath,
          'size' => filesize($filepath),
        ];
        continue;
      }

      // 4f. Check if it's public files.
      if ($this->isPublicFile($relativePath)) {
        $categories['public_files']['included'][] = [
          'path' => $relativePath,
          'size' => filesize($filepath),
          'human' => $this->formatBytes(filesize($filepath)),
        ];
        $categories['metadata']['total_size_bytes'] += filesize($filepath);
        $categories['metadata']['total_files']++;
      }
    }

    // 5. AGGREGATE STATS.
    $categories['public_files']['count'] = count($categories['public_files']['included']);
    $categories['private_files']['count'] = count($categories['private_files']['paths']);
    $categories['sensitive_config']['count'] = count($categories['sensitive_config']['paths']);
    $categories['dependencies']['count'] = count($categories['dependencies']);
    $categories['metadata']['scan_timestamp'] = time();

    return $categories;
  }

  /**
   * Scan project and store results in cache.
   *
   * Used by cron to perform background scanning.
   *
   * @param callable|null $progress_callback
   *   Optional callback to report progress during scan.
   *
   * @return array
   *   The scan results.
   */
  public function scanAndCache(callable $progress_callback = NULL): array {
    // Store previous scan for comparison
    $current_cache = $this->cache->get(self::CACHE_KEY);
    if ($current_cache !== FALSE) {
      $this->cache->set(self::CACHE_KEY_PREVIOUS, $current_cache->data, CacheBackendInterface::CACHE_PERMANENT, ['restic_backup.file_scan']);
    }

    // Perform fresh scan
    $results = $this->scanProject($progress_callback, FALSE);

    // Detect new files
    $results = $this->detectNewFiles($results);

    // Cache results indefinitely until next scan
    $this->cache->set(self::CACHE_KEY, $results, CacheBackendInterface::CACHE_PERMANENT, ['restic_backup.file_scan']);

    return $results;
  }

  /**
   * Detect new files by comparing with previous scan.
   *
   * @param array $current_results
   *   The current scan results.
   *
   * @return array
   *   Results with is_new flag added to new files.
   */
  protected function detectNewFiles(array $current_results): array {
    $previous_cache = $this->cache->get(self::CACHE_KEY_PREVIOUS);
    if ($previous_cache === FALSE) {
      // No previous scan, nothing is "new"
      return $current_results;
    }

    $previous_results = $previous_cache->data;

    // Build set of previous file paths for quick lookup
    $previous_paths = [];
    foreach ($previous_results['public_files']['included'] ?? [] as $file) {
      $previous_paths[$file['path']] = TRUE;
    }
    foreach ($previous_results['private_files']['paths'] ?? [] as $file) {
      $previous_paths[$file['path']] = TRUE;
    }
    foreach ($previous_results['sensitive_config']['paths'] ?? [] as $file) {
      $previous_paths[$file['path']] = TRUE;
    }

    // Mark new files in current scan
    foreach ($current_results['public_files']['included'] as &$file) {
      $file['is_new'] = !isset($previous_paths[$file['path']]);
    }
    foreach ($current_results['private_files']['paths'] as &$file) {
      $file['is_new'] = !isset($previous_paths[$file['path']]);
    }
    foreach ($current_results['sensitive_config']['paths'] as &$file) {
      $file['is_new'] = !isset($previous_paths[$file['path']]);
    }

    return $current_results;
  }

  /**
   * Clear file scan cache (force rescan on next access).
   */
  public function clearCache(): void {
    $this->cache->invalidateTags(['restic_backup.file_scan']);
  }

  /**
   * Get the timestamp of the last file scan.
   *
   * @return int|null
   *   Unix timestamp or NULL if never scanned.
   */
  public function getLastScanTime(): ?int {
    $cached = $this->cache->get(self::CACHE_KEY);
    if ($cached !== FALSE && !empty($cached->data['metadata']['scan_timestamp'])) {
      return $cached->data['metadata']['scan_timestamp'];
    }
    return NULL;
  }

  /**
   * Build Restic exclude patterns from file selections.
   *
   * @param array $selections
   *   The file selections from the form.
   *
   * @return array
   *   Array of exclusion patterns for Restic.
   */
  public function buildExclusionList(array $selections): array {
    // TODO: Implement exclusion list builder.
    return [];
  }

  /**
   * Export exclusion patterns to a Restic exclude file.
   *
   * @param array $exclude_patterns
   *   The exclusion patterns.
   * @param string $path
   *   The path to write the file.
   */
  public function exportExclusionFile(array $exclude_patterns, string $path): void {
    // TODO: Implement file export.
  }

  /**
   * Get the project root directory.
   *
   * @return string
   *   The project root path.
   */
  protected function getProjectRoot(): string {
    // Go up from web/ to project root.
    return dirname(\Drupal::root());
  }

  /**
   * Check if .gitignore file exists in project root.
   *
   * @return bool
   *   TRUE if .gitignore exists.
   */
  protected function hasGitignore(): bool {
    return file_exists($this->projectRoot . '/.gitignore');
  }

  /**
   * Check if git command is available.
   *
   * @return bool
   *   TRUE if git is available.
   */
  protected function gitAvailable(): bool {
    $process = new Process(['which', 'git']);
    $process->run();
    return $process->isSuccessful();
  }

  /**
   * Recursively scan directory for all files.
   *
   * @param string $directory
   *   The directory to scan.
   *
   * @return array
   *   Array of absolute file paths.
   */
  protected function recursiveFileScan(string $directory): array {
    $files = [];
    $iterator = new \RecursiveIteratorIterator(
      new \RecursiveDirectoryIterator($directory, \RecursiveDirectoryIterator::SKIP_DOTS),
      \RecursiveIteratorIterator::SELF_FIRST
    );

    foreach ($iterator as $file) {
      if ($file->isFile()) {
        $files[] = $file->getPathname();
      }
    }

    return $files;
  }

  /**
   * Check if file path is ignored by .gitignore using git check-ignore.
   *
   * @param string $relativePath
   *   The relative path from project root.
   *
   * @return bool
   *   TRUE if file is ignored.
   */
  protected function isIgnoredByGit(string $relativePath): bool {
    $process = new Process(['git', 'check-ignore', $relativePath], $this->projectRoot);
    $process->run();
    return $process->getExitCode() === 0;
  }

  /**
   * Check if path is a known dependency directory.
   *
   * @param string $path
   *   The relative path.
   *
   * @return bool
   *   TRUE if path is a dependency.
   */
  protected function isDependency(string $path): bool {
    $dependencies = [
      'vendor/',
      'node_modules/',
      'web/core/',
      'web/libraries/',
    ];

    foreach ($dependencies as $dep) {
      if (strpos($path, $dep) === 0) {
        return TRUE;
      }
    }
    return FALSE;
  }

  /**
   * Check if path is a regenerable file.
   *
   * @param string $path
   *   The relative path.
   *
   * @return bool
   *   TRUE if file is regenerable.
   */
  protected function isRegenerableFile(string $path): bool {
    $regenerables = [
      '#web/sites/.*/files/styles/#',
      '#web/sites/.*/files/css/#',
      '#web/sites/.*/files/js/#',
      '#web/sites/.*/files/php/#',
      '#web/sites/.*/files/advagg_#',
    ];

    foreach ($regenerables as $pattern) {
      if (preg_match($pattern, $path)) {
        return TRUE;
      }
    }
    return FALSE;
  }

  /**
   * Check if path contains sensitive configuration.
   *
   * @param string $path
   *   The relative path.
   *
   * @return bool
   *   TRUE if file is sensitive config.
   */
  protected function isSensitiveConfig(string $path): bool {
    $sensitiveFiles = [
      'settings.local.php',
      'settings.php',
      'services.yml',
      '.env',
      '.env.local',
    ];

    $filename = basename($path);
    if (in_array($filename, $sensitiveFiles)) {
      return TRUE;
    }

    // Pattern matches.
    $sensitivePatterns = ['*.key', '*.pem', '*.ppk'];
    foreach ($sensitivePatterns as $pattern) {
      $regex = str_replace('*', '.*', preg_quote($pattern, '/'));
      if (preg_match("/^{$regex}$/", $filename)) {
        return TRUE;
      }
    }

    return FALSE;
  }

  /**
   * Get the type of sensitive config file.
   *
   * @param string $path
   *   The relative path.
   *
   * @return string
   *   The config type.
   */
  protected function getSensitiveConfigType(string $path): string {
    $filename = basename($path);
    if (strpos($filename, 'settings') !== FALSE) {
      return 'Drupal settings';
    }
    if (strpos($filename, '.env') !== FALSE) {
      return 'Environment config';
    }
    if (strpos($filename, 'services') !== FALSE) {
      return 'Service configuration';
    }
    if (preg_match('/\.(key|pem|ppk)$/', $filename)) {
      return 'Private key/certificate';
    }
    return 'Sensitive configuration';
  }

  /**
   * Check if path is within private files directory.
   *
   * @param string $path
   *   The relative path.
   *
   * @return bool
   *   TRUE if file is in private directory.
   */
  protected function isPrivateFile(string $path): bool {
    $privatePath = $this->getPrivateFilesPath();
    if (empty($privatePath)) {
      return FALSE;
    }
    return strpos($path, $privatePath) === 0;
  }

  /**
   * Get the private files path from Drupal configuration.
   *
   * @return string|null
   *   The private files path or NULL if not configured.
   */
  protected function getPrivateFilesPath(): ?string {
    // Get private stream wrapper configuration.
    $private_path = \Drupal::service('stream_wrapper_manager')
      ->getViaScheme('private')
      ->getDirectoryPath();

    if ($private_path) {
      // Remove DRUPAL_ROOT prefix if present.
      $private_path = str_replace(\Drupal::root() . '/', '', $private_path);
      return $private_path;
    }

    return NULL;
  }

  /**
   * Check if path is within public files directory.
   *
   * @param string $path
   *   The relative path.
   *
   * @return bool
   *   TRUE if file is in public files directory.
   */
  protected function isPublicFile(string $path): bool {
    return (bool) preg_match('#^web/sites/[^/]+/files/#', $path);
  }

  /**
   * Format bytes into human-readable format.
   *
   * @param int $bytes
   *   The number of bytes.
   *
   * @return string
   *   Human-readable format (e.g., "1.5 MB").
   */
  protected function formatBytes(int $bytes): string {
    if ($bytes < 1024) {
      return $bytes . ' B';
    }
    elseif ($bytes < 1048576) {
      return round($bytes / 1024, 2) . ' KB';
    }
    elseif ($bytes < 1073741824) {
      return round($bytes / 1048576, 2) . ' MB';
    }
    else {
      return round($bytes / 1073741824, 2) . ' GB';
    }
  }

}
